# Generated by Django 5.1.3 on 2024-12-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("subscriptionId", models.AutoField(primary_key=True, serialize=False)),
                ("subscriptionName", models.CharField(max_length=128, null=True)),
                ("subscriptionDescription", models.TextField()),
                (
                    "subscriptionPrice",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                ("subscriptionImage", models.CharField(max_length=100, null=True)),
                ("registeredDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription",
            },
        ),
    ]
