# Generated by Django 5.1.3 on 2025-01-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                ("bookId", models.AutoField(primary_key=True, serialize=False)),
                ("bookName", models.CharField(max_length=128)),
                ("bookDescription", models.TextField()),
                ("bookImage", models.CharField(max_length=100, null=True)),
                ("bookPrice", models.IntegerField(blank=True, null=True)),
                ("registeredDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "books",
            },
        ),
    ]
