# Generated by Django 5.1.3 on 2025-01-08 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=32, unique=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "db_table": "account_profile",
            },
        ),
    ]
